apiVersion: v2
name: scipion-portal
version: 0.0.0
appVersion: "0.0.0"
description: A Helm chart to deploy Scipion portal for managing the Scipion instances
icon: file://logo.png
keywords:
- scipion-portal
- scipion
- onedata
type: application
