apiVersion: v1
kind: Service
metadata:
  name: scipion-portal-svc-db
spec:
  type: ClusterIP
  ports:
  - name: scipion-portal-port-db
    port: 3306
    targetPort: 3306
  selector:
    app: scipion-portal-db
