apiVersion: apps/v1
kind: Deployment
metadata:
  name: scipion-portal-db
spec:
  selector:
    matchLabels:
      app: scipion-portal-db
  replicas: 1
  template:
    metadata:
      labels:
        app: scipion-portal-db
    spec:

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: db
        image: mariadb:10.10
        imagePullPolicy: Always

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        ports:
        - containerPort: 3306
        volumeMounts:
        - name: vol-db
          mountPath: "/var/lib/mysql"
        resources:
          limits:
            cpu: {{ .Values.instance.maxcpu }}
            memory: {{ .Values.instance.maxram }}
          requests:
            cpu: {{ .Values.instance.mincpu }}
            memory: {{ .Values.instance.minram }}

        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: mysql_user

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: mysql_password

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: mysql_root_password

      volumes:
      - name: vol-db
        persistentVolumeClaim:
          claimName: pvc-scipion-portal-db
