apiVersion: apps/v1
kind: Deployment
metadata:
  name: scipion-portal-scipo
spec:
  selector:
    matchLabels:
      app: scipion-portal-scipo
  replicas: 1
  template:
    metadata:
      labels:
        app: scipion-portal-scipo
    spec:

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      initContainers:

      - name: init-db-wait
        image: busybox
        imagePullPolicy: Always

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z scipion-portal-svc-db 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']

      - name: init-db-init
        image: mysql
        imagePullPolicy: Always

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        command: ['sh', '-c', 'mysql --host="scipion-portal-svc-db" --user root --password="$MYSQL_ROOT_PASSWORD" --execute="CREATE DATABASE IF NOT EXISTS scipo; GRANT ALL ON scipo.* TO dbuser@;"']
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: mysql_root_password


      containers:

      - name: scipo
        image: hub.cerit.io/scipion-portal/portal:latest
        imagePullPolicy: Always

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: {{ .Values.instance.maxcpu }}
            memory: {{ .Values.instance.maxram }}
          requests:
            cpu: {{ .Values.instance.mincpu }}
            memory: {{ .Values.instance.minram }}

        env:
        - name: OIDC_REDIRECT_URL
          value: {{ .Values.oidc.redirect_url | quote }}

        - name: OIDC_OP_BASE_URL
          value: {{ .Values.oidc.provider_base_url | quote }}

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: secret_key

        - name: OIDC_RP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: oidc_rp_client_id

        - name: OIDC_RP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: oidc_rp_client_secret

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: mysql_user

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scipion-portal-secret
              key: mysql_password
