apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scipion-portal-db
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
