apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scipion-portal-rb
roleRef:
  kind: Role
  name: scipion-portal-r
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: scipion-portal-sa
