on:
  push:
    branches:
    - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to CERIT Harbor registry
      uses: docker/login-action@v2
      with:
        registry: hub.cerit.io
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: hub.cerit.io/scipion-portal/portal:latest
